
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const Licensing = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow py-12 px-4 bg-white">
        <div className="container mx-auto max-w-4xl">
          <h1 className="text-3xl font-bold mb-8">Licensing Information</h1>
          
          <div className="prose max-w-none">
            <p className="text-lg mb-6">
              Shoora's platform contains proprietary content and third-party licensed materials. This document outlines the licensing terms that govern the use of our platform and its contents.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">1. Platform License</h2>
            <p>
              The Shoora platform is licensed to users on a subscription basis, granting access to our legal research tools, AI assistants, and document storage solutions. This license is non-transferable and subject to the subscription terms agreed upon at registration.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">2. Content Licensing</h2>
            <p>
              Legal materials available through the Shoora platform are licensed from various publishers, government sources, and legal content providers. These materials are protected by copyright and other intellectual property laws and may have different usage restrictions.
            </p>
            <ul className="list-disc pl-6 my-4">
              <li>Statutory materials and regulations are generally available for personal and educational use.</li>
              <li>Case law summaries may be used for research but not for commercial republication.</li>
              <li>Proprietary legal commentary and analysis are available for reference only and cannot be reproduced without permission.</li>
            </ul>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">3. AI-Generated Content</h2>
            <p>
              Content generated by our AI assistants is provided for informational purposes only and should not be considered legal advice. The user retains ownership of any unique legal documents or analyses created using our AI tools, subject to our platform's terms of use.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">4. Third-Party Integrations</h2>
            <p>
              Shoora integrates with various third-party services and databases, each with its own licensing terms. Users must comply with the licensing terms of these integrated services when accessing them through our platform.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">5. Academic and Institutional Licensing</h2>
            <p>
              Special licensing arrangements are available for academic institutions, law schools, and research organizations. These institutional licenses provide expanded access rights and usage permissions for educational and research purposes.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">6. Citation Requirements</h2>
            <p>
              When referencing or quoting materials from the Shoora platform in academic works, legal briefs, or other publications, proper citation is required. Citation formats should follow the legal citation standards appropriate for your jurisdiction.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">7. Usage Restrictions</h2>
            <p>
              The following activities are prohibited under our licensing terms:
            </p>
            <ul className="list-disc pl-6 my-4">
              <li>Mass downloading or scraping of content</li>
              <li>Redistribution of proprietary materials to unauthorized users</li>
              <li>Creating derivative databases from our content</li>
              <li>Reverse engineering our AI or search algorithms</li>
              <li>Removing copyright notices or attribution information</li>
            </ul>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">8. Open Access Materials</h2>
            <p>
              Certain materials on the Shoora platform are available under open access licenses. These materials are clearly marked and may be subject to Creative Commons or similar licenses that permit more extensive use and sharing.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">9. Updates to Licensing Terms</h2>
            <p>
              Shoora reserves the right to update these licensing terms at any time. Users will be notified of significant changes to licensing terms that affect their subscription or usage rights.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">10. Contact Information</h2>
            <p>
              For licensing inquiries, including institutional or bulk licensing options, please contact our licensing department at licensing@shoora.com.
            </p>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Licensing;
